"""
pybind11 bindings for ParsedMmapInterface
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['CanDecoder', 'DecodeError', 'DecodedSignal', 'FMT_CANCMD', 'FMT_CANCMD_T2', 'FMT_CANCMD_T3', 'FMT_CANOE', 'FMT_CANOE_CMP', 'FMT_CANOE_FULL', 'FMT_CANSUKE', 'FMT_FILTER', 'FMT_UNKNOWN', 'MessageDef', 'PARSER_STATUS_DONE', 'PARSER_STATUS_ERROR', 'PARSER_STATUS_RUNNING', 'ParsedEntry', 'ParsedMmapInterface', 'SignalDef', 'abi_version', 'can_decoder_run', 'parse_file', 'parse_file_with_fmt', 'parse_line', 'run_worker_segmented']
class CanDecoder:
    def __init__(self) -> None:
        ...
    def decode_entry(self, entry: ParsedEntry, max_signals: typing.SupportsInt | typing.SupportsIndex = 0) -> list[DecodedSignal]:
        ...
    def free_db(self) -> None:
        ...
    def is_loaded(self) -> bool:
        ...
    def load_db(self, messages: collections.abc.Sequence[MessageDef], signals: collections.abc.Sequence[SignalDef]) -> int:
        ...
class DecodeError:
    error_message: str
    def __init__(self) -> None:
        ...
    @property
    def rc(self) -> int:
        ...
    @rc.setter
    def rc(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class DecodedSignal:
    signal_name: str
    def __init__(self) -> None:
        ...
    @property
    def phys_value(self) -> float:
        ...
    @phys_value.setter
    def phys_value(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def raw_value(self) -> int:
        ...
    @raw_value.setter
    def raw_value(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class MessageDef:
    def __init__(self) -> None:
        ...
    @property
    def can_id(self) -> int:
        ...
    @can_id.setter
    def can_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def msg_length(self) -> int:
        ...
    @msg_length.setter
    def msg_length(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def padding(self) -> int:
        ...
    @padding.setter
    def padding(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def signal_count(self) -> int:
        ...
    @signal_count.setter
    def signal_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def signal_offset(self) -> int:
        ...
    @signal_offset.setter
    def signal_offset(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class ParsedEntry:
    channel: str
    def __init__(self) -> None:
        ...
    @property
    def can_id(self) -> int:
        ...
    @can_id.setter
    def can_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def changed(self) -> int:
        ...
    @changed.setter
    def changed(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def data(self) -> list[int]:
        ...
    @data.setter
    def data(self, arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def data_len(self) -> int:
        ...
    @data_len.setter
    def data_len(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def direction(self) -> int:
        ...
    @direction.setter
    def direction(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_timestamp(self) -> float:
        ...
    @last_timestamp.setter
    def last_timestamp(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def line_number(self) -> int:
        ...
    @line_number.setter
    def line_number(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def timestamp(self) -> float:
        ...
    @timestamp.setter
    def timestamp(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class ParsedMmapInterface:
    def __init__(self, token_id: str) -> None:
        ...
    def close_mmap(self) -> None:
        ...
    def fetch_count(self) -> int:
        ...
    def get_first_last_timestamp(self) -> tuple:
        ...
    def last_error_code(self) -> int:
        ...
    def open_mmap(self) -> int:
        ...
    def read_all_entries(self) -> list[ParsedEntry]:
        ...
    def read_page(self, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_can_id(self, can_id: typing.SupportsInt | typing.SupportsIndex, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_can_id_changed(self, can_id: typing.SupportsInt | typing.SupportsIndex, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_can_ids(self, can_ids: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_can_ids_changed(self, can_ids: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_channel(self, channel: str, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_channels(self, channels: collections.abc.Sequence[str], first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_direction(self, direction: str, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_from_directions(self, directions: collections.abc.Sequence[str], first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def write_entries(self, parsed_entries: collections.abc.Sequence[ParsedEntry]) -> int:
        ...
class SignalDef:
    def __init__(self) -> None:
        ...
    @property
    def bit_length(self) -> int:
        ...
    @bit_length.setter
    def bit_length(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def byte_order(self) -> int:
        ...
    @byte_order.setter
    def byte_order(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def has_choices(self) -> int:
        ...
    @has_choices.setter
    def has_choices(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def is_signed(self) -> int:
        ...
    @is_signed.setter
    def is_signed(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def offset(self) -> float:
        ...
    @offset.setter
    def offset(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def padding1(self) -> int:
        ...
    @padding1.setter
    def padding1(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def scale(self) -> float:
        ...
    @scale.setter
    def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def start_bit(self) -> int:
        ...
    @start_bit.setter
    def start_bit(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
def abi_version() -> int:
    ...
def can_decoder_run(parsed_mmap_token: str, decoder: CanDecoder) -> DecodeError:
    ...
def parse_file(path: str) -> list[ParsedEntry]:
    ...
def parse_file_with_fmt(path: str, fmt: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
    ...
def parse_line(line: str, line_num: typing.SupportsInt | typing.SupportsIndex = 0) -> typing.Any:
    ...
def run_worker_segmented(file_path: str, token_id: str, fmt: typing.SupportsInt | typing.SupportsIndex) -> int:
    ...
FMT_CANCMD: int = 4
FMT_CANCMD_T2: int = 7
FMT_CANCMD_T3: int = 8
FMT_CANOE: int = 1
FMT_CANOE_CMP: int = 3
FMT_CANOE_FULL: int = 2
FMT_CANSUKE: int = 6
FMT_FILTER: int = 5
FMT_UNKNOWN: int = 0
PARSER_STATUS_DONE: int = 1
PARSER_STATUS_ERROR: int = 2
PARSER_STATUS_RUNNING: int = 0
