"""
pybind11 bindings for MetaDataStorageInterface
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['CanDatabaseModel', 'CanDecoder', 'DecodeError', 'DecodedSignal', 'EntryUpdate', 'FMT_CANCMD', 'FMT_CANCMD_T2', 'FMT_CANCMD_T3', 'FMT_CANOE', 'FMT_CANOE_CMP', 'FMT_CANOE_FULL', 'FMT_CANSUKE', 'FMT_FILTER', 'FMT_UNKNOWN', 'LogQuery', 'LogRecord', 'MessageDef', 'MetaDataStorageInterface', 'PARSER_STATUS_DONE', 'PARSER_STATUS_ERROR', 'PARSER_STATUS_RUNNING', 'ParsedEntry', 'SignalDef', 'abi_version', 'can_decoder_run', 'parse_file', 'parse_file_with_fmt', 'parse_line', 'run_worker_segmented']
class CanDatabaseModel:
    def __init__(self) -> None:
        ...
    @property
    def canid_to_msg(self) -> dict[int, int]:
        ...
    @canid_to_msg.setter
    def canid_to_msg(self, arg0: collections.abc.Mapping[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def messages(self) -> list[MessageDef]:
        ...
    @messages.setter
    def messages(self, arg0: collections.abc.Sequence[MessageDef]) -> None:
        ...
    @property
    def signals(self) -> list[SignalDef]:
        ...
    @signals.setter
    def signals(self, arg0: collections.abc.Sequence[SignalDef]) -> None:
        ...
class CanDecoder:
    def __init__(self) -> None:
        ...
    def decode_entry(self, entry: LogRecord, max_signals: typing.SupportsInt | typing.SupportsIndex = 0) -> list[DecodedSignal]:
        ...
    def free_db(self) -> None:
        ...
    def is_loaded(self) -> bool:
        ...
    def load_db(self, messages: collections.abc.Sequence[MessageDef], signals: collections.abc.Sequence[SignalDef]) -> int:
        ...
class DecodeError:
    error_message: str
    def __init__(self) -> None:
        ...
    @property
    def rc(self) -> int:
        ...
    @rc.setter
    def rc(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class DecodedSignal:
    signal_name: str
    def __init__(self) -> None:
        ...
    @property
    def phys_value(self) -> float:
        ...
    @phys_value.setter
    def phys_value(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def raw_value(self) -> int:
        ...
    @raw_value.setter
    def raw_value(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class EntryUpdate:
    record: LogRecord
    def __init__(self) -> None:
        ...
    @property
    def row_index(self) -> int:
        ...
    @row_index.setter
    def row_index(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class LogQuery:
    changed_only: bool
    has_time_range: bool
    def __init__(self) -> None:
        ...
    @property
    def can_ids(self) -> list[int]:
        ...
    @can_ids.setter
    def can_ids(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def channels(self) -> list[str]:
        ...
    @channels.setter
    def channels(self, arg0: collections.abc.Sequence[str]) -> None:
        ...
    @property
    def directions(self) -> list[int]:
        ...
    @directions.setter
    def directions(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def first_ts(self) -> float:
        ...
    @first_ts.setter
    def first_ts(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def last_ts(self) -> float:
        ...
    @last_ts.setter
    def last_ts(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class LogRecord:
    channel: str
    def __init__(self) -> None:
        ...
    @property
    def can_id(self) -> int:
        ...
    @can_id.setter
    def can_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def data(self) -> list[int]:
        ...
    @data.setter
    def data(self, arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def data_len(self) -> int:
        ...
    @data_len.setter
    def data_len(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def direction(self) -> int:
        ...
    @direction.setter
    def direction(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def timestamp(self) -> float:
        ...
    @timestamp.setter
    def timestamp(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class MessageDef:
    def __init__(self) -> None:
        ...
    @property
    def can_id(self) -> int:
        ...
    @can_id.setter
    def can_id(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def msg_length(self) -> int:
        ...
    @msg_length.setter
    def msg_length(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def padding(self) -> int:
        ...
    @padding.setter
    def padding(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def signal_count(self) -> int:
        ...
    @signal_count.setter
    def signal_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def signal_offset(self) -> int:
        ...
    @signal_offset.setter
    def signal_offset(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class MetaDataStorageInterface:
    def __init__(self, mmap_prefix: str) -> None:
        ...
    def close_mmap(self) -> None:
        ...
    def close_storage(self) -> None:
        ...
    def fetch_count(self) -> int:
        ...
    def get_file_path(self) -> str:
        ...
    def get_first_last_timestamp(self) -> typing.Optional[tuple[float, float]]:
        ...
    def last_error_code(self) -> int:
        ...
    def open_mmap(self) -> int:
        ...
    def open_storage(self) -> None:
        ...
    def read_all_entries(self) -> list[ParsedEntry]:
        ...
    def read_page(self, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def read_page_multi(self, query: LogQuery, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
        ...
    def update_entries(self, entry_updates: collections.abc.Sequence[EntryUpdate]) -> None:
        ...
    def write_entries(self, parsed_entries: collections.abc.Sequence[LogRecord]) -> None:
        ...
class ParsedEntry(LogRecord):
    def __init__(self) -> None:
        ...
    @property
    def changed(self) -> int:
        ...
    @changed.setter
    def changed(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def last_timestamp(self) -> float:
        ...
    @last_timestamp.setter
    def last_timestamp(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def line_number(self) -> int:
        ...
    @line_number.setter
    def line_number(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class SignalDef:
    def __init__(self) -> None:
        ...
    @property
    def bit_length(self) -> int:
        ...
    @bit_length.setter
    def bit_length(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def byte_order(self) -> int:
        ...
    @byte_order.setter
    def byte_order(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def has_choices(self) -> int:
        ...
    @has_choices.setter
    def has_choices(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def is_signed(self) -> int:
        ...
    @is_signed.setter
    def is_signed(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def offset(self) -> float:
        ...
    @offset.setter
    def offset(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def padding1(self) -> int:
        ...
    @padding1.setter
    def padding1(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def scale(self) -> float:
        ...
    @scale.setter
    def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def start_bit(self) -> int:
        ...
    @start_bit.setter
    def start_bit(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
def abi_version() -> int:
    ...
def can_decoder_run(parsed_mmap_token: str, model: CanDatabaseModel) -> DecodeError:
    ...
def parse_file(path: str) -> list[ParsedEntry]:
    ...
def parse_file_with_fmt(path: str, fmt: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]:
    ...
def parse_line(line: str) -> typing.Any:
    ...
def run_worker_segmented(file_path: str, token_id: str) -> int:
    ...
FMT_CANCMD: int = 4
FMT_CANCMD_T2: int = 7
FMT_CANCMD_T3: int = 8
FMT_CANOE: int = 1
FMT_CANOE_CMP: int = 3
FMT_CANOE_FULL: int = 2
FMT_CANSUKE: int = 6
FMT_FILTER: int = 5
FMT_UNKNOWN: int = 0
PARSER_STATUS_DONE: int = 1
PARSER_STATUS_ERROR: int = 2
PARSER_STATUS_RUNNING: int = 0
