import collections.abc
import typing

class CanDatabaseModel:
    canid_to_msg: dict[int, int]
    messages: list[MessageDef]
    signals: list[SignalDef]
    def __init__(self) -> None: ...

class CanDecoder:
    def __init__(self) -> None: ...
    def decode_entry(self, entry: LogRecord, max_signals: typing.SupportsInt | typing.SupportsIndex = ...) -> list[DecodedSignal]: ...
    def free_db(self) -> None: ...
    def is_loaded(self) -> bool: ...
    def load_db(self, messages: collections.abc.Sequence[MessageDef], signals: collections.abc.Sequence[SignalDef]) -> int: ...

class DataMmapReader:
    def __init__(self, arg0: str) -> None: ...
    def read_page(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]: ...

class DataMmapWriter:
    def __init__(self, arg0: str) -> None: ...
    def append_entry(self, arg0: ParsedEntry) -> int: ...

class DecodeError:
    error_message: str
    rc: int
    def __init__(self) -> None: ...

class DecodedSignal:
    phys_value: float
    raw_value: int
    signal_name: str
    def __init__(self) -> None: ...

class LogQuery:
    can_ids: list[int]
    changed_only: bool
    channels: list[str]
    directions: list[int]
    first_ts: float
    has_time_range: bool
    last_ts: float
    def __init__(self) -> None: ...

class LogRecord:
    can_id: int
    channel: str
    data: bytes
    data_len: int
    direction: int
    timestamp: float
    def __init__(self) -> None: ...

class MessageDef:
    can_id: int
    msg_length: int
    padding: int
    signal_count: int
    signal_offset: int
    def __init__(self) -> None: ...

class MetaDataStorageInterface:
    def __init__(self, mmap_prefix: str) -> None: ...
    def fetch_count(self) -> int: ...
    def get_first_last_timestamp(self) -> object: ...
    def read_page(self, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]: ...
    def read_page_multi(self, query: LogQuery, first: typing.SupportsInt | typing.SupportsIndex, last: typing.SupportsInt | typing.SupportsIndex) -> list[ParsedEntry]: ...
    def token_path(self) -> str: ...
    def update_entry(self, row_index: typing.SupportsInt | typing.SupportsIndex, entry: LogRecord) -> None: ...
    def write_entries(self, parsed_entries: collections.abc.Sequence[LogRecord]) -> None: ...

class ParsedEntry(LogRecord):
    changed: int
    last_timestamp: float
    line_number: int
    def __init__(self) -> None: ...

class SignalDef:
    bit_length: int
    byte_order: int
    has_choices: int
    is_signed: int
    offset: float
    padding1: int
    scale: float
    start_bit: int
    def __init__(self) -> None: ...

def abi_version() -> int: ...
def can_decoder_run(parsed_mmap_token: str, model: CanDatabaseModel) -> DecodeError: ...
def parse_line(line: str) -> object: ...
def parse_lines(src: str) -> list[LogRecord]: ...
def run_worker_segmented(file_path: str, token_id: str) -> int: ...

