from __future__ import annotations

from typing import Iterable, Sequence


def abi_version() -> int: ...


class ParsedEntry:
    line_number: int
    timestamp: float
    last_timestamp: float
    can_id: int
    direction: int
    data_len: int
    changed: list[int]

    def __init__(self) -> None: ...


class ParsedMmapInterface:
    def __init__(self, token_id: str) -> None: ...

    def open_mmap(self) -> None: ...
    def write_entries(self, parsed_entries: Iterable[ParsedEntry]) -> None: ...
    def close_mmap(self) -> None: ...

    def read_page(self, first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_can_id(self, can_id: int, first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_can_ids(self, can_ids: Sequence[int], first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_can_id_changed(self, can_id: int, first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_can_ids_changed(self, can_ids: Sequence[int], first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_channel(self, channel: str, first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_channels(self, channels: Sequence[str], first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_direction(self, direction: str, first: int, last: int) -> list[ParsedEntry]: ...
    def read_page_from_directions(self, directions: Sequence[str], first: int, last: int) -> list[ParsedEntry]: ...

    def get_total_entries_num(self) -> int: ...
    def last_error_code(self) -> int: ...
